permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: ":num"
baseurl: ""



title: "RainyAlley"
email: "dubuyuye@yeah.net"
description: "Developer"
github_username:  "dubuyuye"
swiftype_searchId: "ncwR9a8S9CTx2q9SgsJm"
disqus_shortname: "rainyalley"



#url: "http://blog.rainyalley.com"
#imgrepo: "http://blog.rainyalley.com/static/img"


url: "http://101.201.198.151:4000"
imgrepo: "http://101.201.198.151:4000/static/img"
gems: [jekyll-paginate]

